language: java
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "charlemaznable"
script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=CharLemAznable_gentle-boot
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success:
  - bash <(curl -s https://codecov.io/bash)
